name: Build Android App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Flavor"
        required: true
        default: "staging"
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  flutter_version: "3.24.3" # TODO: Put on variables

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v4 #to install firebase CLI
      #   with:
      #     node-version: 20

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: "stable"
          cache: true # Cache to reduce cost and time up to 50%
      - run: flutter --version

      - name: Cache Flutter build folder
        uses: actions/cache@v2
        with:
          path: build
          key: build-cache-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}-${{ hashFiles('flutter --version') }} # Cache to reduce cost and time up to 50%
          restore-keys: |
            build-cache-${{ runner.os }}-

      - name: Install flutter dependencies
        run: flutter pub get

      - name: Create Android key.properties file
        run: echo -n "$ANDROID_KEY_PROPERTIES_BASE64" | base64 --decode > android/key.properties
        env:
          ANDROID_KEY_PROPERTIES_BASE64: ${{ secrets.ANDROID_KEY_PROPERTIES_BASE64 }}

      - name: Create Android JKS file
        run: echo -n "$ANDROID_SIGNING_KEY_STORE_BASE64" | base64 --decode > android/app/code_challenge.jks
        env:
          ANDROID_SIGNING_KEY_STORE_BASE64: ${{ secrets.ANDROID_SIGNING_KEY_STORE_BASE64 }}

      - name: Build App release
        run: flutter build apk -t lib/${{ inputs.environment }}_main.dart --flavor ${{ inputs.environment }} --release # Change for flutter build appbundle -t lib/${{ inputs.environment }}_main.dart --flavor ${{ inputs.environment }} --release to generate an .aab for Google Play Store.

 ## Send to firebase app distribution or google play store(close test, internal test, production) with fastlane or some action
# - name: Install Firebase CLI
#         run: npm install -g firebase-tools
#  firebase appdistribution:distribute build/app/outputs/flutter-apk/app-${{ inputs.environment }}-release.apk \
#   --app ??? \
#   --release-notes-file "notes.txt" \
#   --groups "???"
